"""Shared constants for the SequoiaDB Python driver."""

EYE_DEFAULT = 0x0000EEEE
HEADER_SIZE = 52
REPLY_MASK = 0x40000000

# Error codes (negative = error, matching C++ convention)
SDB_OK = 0
SDB_SYS = -1
SDB_OOM = -2
SDB_INVALID_ARG = -6
SDB_PERMISSION_DENIED = -7
SDB_NETWORK_ERROR = -15
SDB_NETWORK_CLOSE = -16
SDB_TIMEOUT = -17
SDB_COLLECTION_ALREADY_EXISTS = -22
SDB_COLLECTION_NOT_FOUND = -23
SDB_NOT_FOUND = -29
SDB_QUERY_NOT_FOUND = -31
SDB_CS_ALREADY_EXISTS = -33
SDB_CS_NOT_FOUND = -34
SDB_DUPLICATE_KEY = -38
SDB_INDEX_ALREADY_EXISTS = -46
SDB_INDEX_NOT_FOUND = -47
SDB_EOF = -9
SDB_AUTH_FAILED = -179
SDB_TRANSACTION_ERROR = -253
